version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@google-cloud/firestore"
    versions:
    - 4.9.1
    - 4.9.2
    - 4.9.3
    - 4.9.4
    - 4.9.6
    - 4.9.7
    - 4.9.8
    - 4.9.9
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: express-validator
    versions:
    - 6.10.0
    - 6.9.2
  - dependency-name: lodash
    versions:
    - 4.17.20
- package-ecosystem: npm
  directory: "/test"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
