language: node_js
node_js: 10
before_install:
  - openssl aes-256-cbc -K $encrypted_e5776bea95d0_key -iv $encrypted_e5776bea95d0_iv
    -in ci-key.json.enc -out ci-key.json -d
before_script:
  - chmod +x test-ci.sh
  - yarn build
  - cd test && yarn install
  - cd ..
script: yarn run test:ci
